-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE ACTOR (
ActorGenre VARCHAR(20),
Cpf VARCHAR(15),
HourValue FLOAT,
FK_IdUser INT
)

CREATE TABLE RESERVATION (
Id INT PRIMARY KEY,
TotalValue FLOAT,
DateReservation DATETIME,
FK_IdUser INT
)

CREATE TABLE USER (
Id INT PRIMARY KEY,
Senha ,
FirstName VARCHAR(20),
LasName VARCHAR(50),
Email VARCHAR(100),
Cellphone VARCHAR(14),
DateCreatedAccount DATETIME
)

CREATE TABLE PRODUCER (
FantasyName VARCHAR(50),
Cnpj VARCHAR(30),
FK_IdUser INT,
FOREIGN KEY(FK_IdUser) REFERENCES USER (Id)
)

CREATE TABLE LOGS (
Id INT PRIMARY KEY,
ErrorsLogs VARCHAR(500),
TrackingsLogs VARCHAR(500),
SecuritiesLogs VARCHAR(500)
)

CREATE TABLE reservation_generate  (
FK_IdReservation INT,
FK_IdLogs INT,
FOREIGN KEY(FK_IdReservation) REFERENCES RESERVATION (Id),
FOREIGN KEY(FK_IdLogs) REFERENCES LOGS (Id)
)

CREATE TABLE user_generate  (
FK_IdUser INT,
FK_IdLogs INT,
FOREIGN KEY(FK_IdUser) REFERENCES USER (Id),
FOREIGN KEY(FK_IdLogs) REFERENCES LOGS (Id)
)

ALTER TABLE ACTOR ADD FOREIGN KEY(FK_IdUser) REFERENCES USER (Id)
ALTER TABLE RESERVATION ADD FOREIGN KEY(FK_IdUser) REFERENCES USER (Id)
